# Travis CI Settings
#-------------------

language: android
# Turning off caching to avoid caching Issues
cache: false
# Using the new Container-Based Infrastructure
sudo: false
env:
  global:
# Initiating clean Gradle output
    - TERM=dumb
# Amount of memory granted to Gradle JVM
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
# General Android settings used in builds
    - ANDROID_TARGET=android-21
    - ANDROID_ABI=armeabi-v7a

before_install:
# Making sure gradlew has executable permissions
    - chmod +x gradlew

android:
  components:
# We are using the latest revision of Android SDK Tools
     - platform-tools
     - tools
# The BuildTools version we are using for our project
     - build-tools-21.1.1
# System Image we use to run emulator(s) during tests
     - sys-img-armeabi-v7a-android-21

  licenses:
     - 'android-sdk-license-.+'

# Emulator Management: Create, Start and Wait
before_script:
# Inspecting running services
     - ps auxww
     - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
     - emulator -avd test -no-skin -no-audio -no-window &
     - android-wait-for-emulator
     - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest --info

notifications:
  slack:
    rooms:
      - psu2014:Y8aJDZfDewFhwDBZqbM8D8Pt#android

addons:
# Scan results: http://scan.coverity.com/projects/3346
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew build"
    branch_pattern: master

    